Looks like we need 1.6.2 targets throughout
It seems "Encoding" class may have moved from one namespace/assembly to another
causing a breaking change, meaning 1.6.2 can't target 1.6 stuff

Theory isn't proven yet, compile still breaks for netcoreapp1.2 target:

"error CS0433: The type 'Encoding' exists in both 'System.Text.Encoding, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'"